### ISSUE TITLE
 Provide filename into error so reporter can use it

### ISSUE THREAD

**Issue by MoOx** [webpack/jshint-loader#11]
I like [GNU like message](https://www.gnu.org/prep/standards/html_node/Errors.html) and I would like to be able to output message like this

```
/.../filename.ext:line:column: message
```

Example:

```
web_modules/component/index.js:42:1337: This error make me sad (reason - code)
```

But right now I can not do that :(

**Comment by MoOx** [comment]
Adding `source` as param for the reporter should do the trick, don't you think ?

**Comment by sokra** [comment]
You can pass a custom reporter...

**Comment by MoOx** [comment]
Yeah, but can't access the filename. It's not accessible.

**Comment by Dashed** [comment]
@MoOx 
The caveat is that the reporter for jshint-loader is called for every file; and thus the jshint output is only on one file, not a list of them.

webpack provides `this.emitWarning` function, which you can use to emit jshint output. When using it, it will output which file the output is associated with.

For example for my custom reporter:

```
WARNING in ./src/index.js

jshint report:
  line 20  col 17  Missing 'new' prefix when invoking a constructor.  (W064)  
            let Store = StoreSnapshot();

  ⚠  1 warning
```

Here's my custom reporter: https://gist.github.com/Dashed/ed941052b82fd7694320
