### ISSUE TITLE
Not reading my .jshintrc

### ISSUE THREAD

**Issue by kentcdodds** [webpack/jshint-loader#13]
I'm not sure what changed, but webpack seems to not be applying my `.jshintrc` anymore. When I change my `.jshintrc` to end with `.json` and require it in my webpack config on the `jshint` property, everything works as expected.

**Comment by unindented** [comment]
@sokra This is caused by this commit in rcloader: https://github.com/spenceralger/rcloader/commit/355d6e771553c72b715f7df5d6259f6818cc987f

I've got the same problem in my loader https://github.com/unindented/jscs-loader. How do you want to handle this?

**Comment by sokra** [comment]
Can we change it to this?

``` js
var rcLoader = new RcLoader(".jshintrc", null, {
	loader: function(path) {
		return { path: path };
	}
});
```

**Comment by unindented** [comment]
Yep, that should work fine. Do you want to wait until the owner of `rcloader` chimes in the discussion?

**Comment by Dashed** [comment]
If at all possible, for now, do workaround at jshint-loader and related plugins Otherwise, `rcloader` would be blocking.

This may not be a trivial fix on `rcloader`'s end.

**Comment by yordis** [comment]
@unindented any update on this ticket. Is fixed?

**Comment by sokra** [comment]
I think so.

**Comment by Dashed** [comment]
Might want to consider this: https://github.com/spalger/rcloader/pull/3#commitcomment-9640184
