### ISSUE TITLE
Add tests & setup travis

### ISSUE THREAD

**Issue by kostasmanionis** [webpack/jshint-loader#23]
Need add tests and setup travis. We should probably look into what other loaders are using and keep it consistent. `html-loader` looks like a nice example.

**Comment by sidjain26** [comment]
Any consensus on what testing framework/utilities need to be used?

**Comment by kostasmanionis** [comment]
Well we have free reign to choose whatever we want. But AFAIK most loaders will probably use whatever webpack uses.

That would be mocha+should.js. I'm fine with using these. Thoughts? @sidjain26 you want to take a shot at this?
