### ISSUE TITLE
Respect .jshintrc

### ISSUE THREAD

**Issue by avanderhoorn** [webpack/jshint-loader#6]
Just wondering if the package can be updated to respect the `.jshintrc` file if it present. 

As per there docs:
 > There are three main ways to configure your copy of JSHint: you can either specify the configuration file manually via the --config flag, use a special file .jshintrc or put your config into your projects package.json file under the jshintConfig property. In case of .jshintrc, JSHint will start looking for this file in the same directory as the file that's being linted.

This would be nice as other tools (like various IDE linters) look for this file and adjust the running errors accordingly.

**Comment by MoOx** [comment]
I guess this issue has been closed by #8

**Comment by Dashed** [comment]
Yep it has. Been working great so far.
